class EnvironmentSettings:
    def __init__(self):
        self.workspace_dir = '/data1/xuelin/xuelin/stark6'    # Base directory for saving network checkpoints.
        self.tensorboard_dir = '/data1/xuelin/xuelin/stark6/tensorboard'    # Directory for tensorboard files.
        self.pretrained_networks = '/data1/xuelin/xuelin/stark6/pretrained_networks'
        self.lasot_dir = '/data1/xuelin/xuelin/VideoX-master/SeqTrack/data/lasot'
        self.got10k_dir = '/data1/xuelin/xuelin/VideoX-master/SeqTrack/data/got10k/'
        self.lasot_lmdb_dir = '/data1/xuelin/xuelin/VideoX-master/SeqTrack/data/lasot_lmdb'
        self.got10k_lmdb_dir = '/data1/xuelin/xuelin/VideoX-master/SeqTrack/data/got10k_lmdb'
        self.trackingnet_dir = '/data1/xuelin/xuelin/VideoX-master/SeqTrack/data/trackingnet'
        self.trackingnet_lmdb_dir = '/data1/xuelin/xuelin/VideoX-master/SeqTrack/data/trackingnet_lmdb'
        self.coco_dir = '/data1/xuelin/xuelin/VideoX-master/SeqTrack/data/coco'
        self.coco_lmdb_dir = '/data1/xuelin/xuelin/VideoX-master/SeqTrack/data/coco_lmdb'
        self.lvis_dir = ''
        self.sbd_dir = ''
        self.imagenet_dir = '/data1/xuelin/xuelin/VideoX-master/SeqTrack/data/vid'
        self.imagenet_lmdb_dir = '/data1/xuelin/xuelin/VideoX-master/SeqTrack/data/vid_lmdb'
        self.imagenetdet_dir = ''
        self.ecssd_dir = ''
        self.hkuis_dir = ''
        self.msra10k_dir = ''
        self.davis_dir = ''
        self.youtubevos_dir = ''
        self.tnl2k_dir = '/data1/xuelin/xuelin/VideoX-master/SeqTrack/data/tnl2k'
        self.otb_lang_dir = '/data1/xuelin/xuelin/VideoX-master/SeqTrack/data/otb_lang'
        self.ref_coco_dir = '/data1/xuelin/xuelin/VideoX-master/SeqTrack/data/ref_coco'
